### ISSUE TITLE
XYZ Image File Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPGMaker-Specifications#4]
Complete the specification for XYZ image files.

- [x] Create a document.
- [x] Preliminary research and outline.
- [x] Complete research and begin finalization.
- [x] Finish finalizing and mark specification as complete.
