### ISSUE TITLE
LMT Map Tree File Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPGMaker-Specifications#5]
Complete the specification for LMT map tree files.

- [x] Create a document.
- [x] Preliminary research and outline.
- [x] Complete research and begin finalization.
- [x] Finish finalizing and mark specification as complete.
