### ISSUE TITLE
RPG_RT.ini File Specification

### ISSUE THREAD

**Issue by napen123** [chika-games/RPGMaker-Specifications#6]
Complete the specification for RPG_RT.ini files.

- [x] Create a document and mark as _Researching_.
- [x] Preliminary research and outline.
- [x] Complete research and begin finalization.
- [x] Finish finalizing and mark specification as complete.

**Comment by napen123** [comment]
## INI Fields
| Key | Description |
| --- | --- |
| GameTitle | The title of the window's window.  |
| MapEditMode | ??? |
| MapEditZoom | ??? |
| FullPackageFlag | ??? |
